version: '3.8'

services:
  wordapp:
    platform: linux/amd64
    image: wordapp:latest
    container_name: wordapp_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development